-- Migration 0034: Patient After-Visit Summary and Discharge Summary storage
-- Stores generated PDFs for the clinician → admin → patient print workflow

CREATE TABLE IF NOT EXISTS patient_summaries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id UUID NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  -- visit_id references medical_records.id for OPD (avs) or admissions.id for inpatient (discharge)
  visit_id UUID NOT NULL,
  visit_type TEXT NOT NULL CHECK (visit_type IN ('avs', 'discharge')),
  generated_by UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  status TEXT NOT NULL DEFAULT 'pending_print'
    CHECK (status IN ('pending_print', 'printed', 'unlocked')),
  pdf_data BYTEA NOT NULL,
  unlocked_by UUID REFERENCES users(id) ON DELETE SET NULL,
  unlocked_at TIMESTAMPTZ,
  unlock_reason TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_patient_summaries_patient ON patient_summaries(patient_id, generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_patient_summaries_status ON patient_summaries(status);
CREATE INDEX IF NOT EXISTS idx_patient_summaries_visit ON patient_summaries(visit_id);

COMMENT ON TABLE patient_summaries IS 'Clinician-generated PDFs (AVS and discharge summaries) pending admin printing';
COMMENT ON COLUMN patient_summaries.visit_id IS 'References medical_records.id for avs, admissions.id for discharge';
COMMENT ON COLUMN patient_summaries.pdf_data IS 'Raw PDF bytes generated by PDFKit';
