/**
 * Non-medication inventory: categories (item_type) and suggested subtypes per category.
 * Single source of truth for frontend dropdowns and API validation.
 */

export const NON_MEDICATION_CATEGORIES = [
  "Medical Equipment",
  "Diagnostic Equipment",
  "Surgical & Procedure Equipment",
  "Personal Protective Gear",
  "Patient Care Items",
  "Consumables and Supplies",
  "Office Supplies",
] as const

export type NonMedicationCategory = (typeof NON_MEDICATION_CATEGORIES)[number]

export const NON_MEDICATION_SUBTYPES: Record<NonMedicationCategory, readonly string[]> = {
  "Medical Equipment": [
    "Stethoscope",
    "Blood pressure monitor",
    "Thermometer",
    "Weighing scale",
    "Nebulizer",
    "Oxygen concentrator",
    "Suction machine",
    "Patient monitor",
    "IV stand",
    "Wheelchair",
    "Crutches",
    "Walking stick",
    "Bedpan",
    "Urinal",
    "Heating pad",
    "Ice pack",
    "Resuscitator bag",
    "Oxygen mask and tubing",
    "Suction catheter",
    "Oropharyngeal airway",
    "Laryngoscope",
    "Endotracheal tubes",
    "Vaginal speculum",
    "Sterilizer",
    "Autoclave",
    "Spirometer",
    "Holter monitor",
    "Fetal monitor",
    "Surgical table",
    "Utility cart",
    "Splints",
  ],
  "Diagnostic Equipment": [
    "Glucometer",
    "Pulse oximeter",
    "ECG machine",
    "X-ray viewer",
    "X-ray machine",
    "Ultrasound machine",
    "Otoscope",
    "Ophthalmoscope",
    "Digital thermometer",
    "Infrared thermometer",
    "Fetoscope",
    "Doppler",
    "Sphygmomanometer",
    "Blood analyzer",
    "Urine analyzer",
    "Laryngoscope",
    "Speculum",
  ],
  "Surgical & Procedure Equipment": [
    "Surgical gloves",
    "Scalpel",
    "Forceps",
    "Scissors",
    "Sutures",
    "Syringes",
    "Needles",
    "IV sets",
    "Catheters",
    "Specimen containers",
    "Gauze",
    "Bandages",
    "Drapes",
    "Retractors",
    "Needle holders",
    "Cautery device",
    "Nasogastric tubes",
    "IV cannulas",
    "Chest tube set",
    "Sharps container",
  ],
  "Personal Protective Gear": [
    "Gloves",
    "Masks",
    "Gowns",
    "Face shields",
    "Goggles",
    "Shoe covers",
    "Caps",
    "N95 masks",
    "Aprons",
  ],
  "Patient Care Items": [
    "Bed sheets",
    "Pillows",
    "Blankets",
    "Wash basins",
    "Soap dispensers",
    "Hand sanitizer",
    "Clipboards",
    "Towels",
    "Sanitary bins",
  ],
  "Consumables and Supplies": [
    "Cotton wool",
    "Cotton balls",
    "Swabs",
    "Tape",
    "Disinfectant",
    "Wound dressings",
    "Alcohol pads",
    "Hydrogen peroxide",
    "Medical tape",
    "Tweezers",
    "Sharps containers",
    "Waste disposal containers",
  ],
  "Office Supplies": [
    "Books",
    "Desks",
    "Chairs",
    "Ergonomic chairs",
    "Computers",
    "Keyboards",
    "Mouse",
    "UPS",
    "Monitors",
    "Cables",
    "Printers",
    "Toner/Ink",
    "Paper",
    "Printer paper",
    "Folders",
    "Filing supplies",
    "Staplers",
    "Staples",
    "Pens",
    "Red pens",
    "Mechanical pencils",
    "Notepads",
    "Envelopes",
    "Filing cabinets",
    "Shredders",
    "Whiteboards",
    "Markers",
    "Highlighters",
    "Medical record binders",
    "Dividers and file guides",
    "Manila folders",
    "Patient registration forms",
    "Claim forms",
    "Consent forms",
    "Letterhead",
    "Prescription pads",
    "Laboratory slips",
    "Business cards",
    "Clipboards",
    "Calculators",
    "Labels",
    "Storage cabinets",
    "Shelves",
    "Wastebaskets",
    "Recycling bins",
    "Card scanners",
    "Three-hole punch",
    "Desk organizers",
    "Appointment books",
    "Paper clips",
    "Binder clips",
    "Rubber bands",
    "Tape dispensers",
    "Scissors (office)",
    "Telephone",
    "Headset",
  ],
} as const

export function isValidNonMedicationCategory(value: string): value is NonMedicationCategory {
  return (NON_MEDICATION_CATEGORIES as readonly string[]).includes(value)
}

export function isValidSubtypeForCategory(category: NonMedicationCategory, subtype: string): boolean {
  const list = NON_MEDICATION_SUBTYPES[category]
  return list.includes(subtype)
}
